In [15]:
import numpy as np

a = np.array([[3, 4, 4, 3],
             [2, 4, 6, 6]])
import seaborn as sb
import matplotlib.pyplot as plot


In [5]:
import pandas as pd
data = pd.read_csv('housing.csv')
data.head

<bound method NDFrame.head of        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  ho

In [6]:
data.isna()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False   
1          False     False               False        False           False   
2          False     False               False        False           False   
3          False     False               False        False           False   
4          False     False               False        False           False   
...          ...       ...                 ...          ...             ...   
20635      False     False               False        False           False   
20636      False     False               False        False           False   
20637      False     False               False        False           False   
20638      False     False               False        False           False   
20639      False     False               False        False           False   

       population  households  median_income  median_house_value  \
0           False       False          False               False   
1           False       False          False               False   
2           False       False          False               False   
3           False       False          False               False   
4           False       False          False               False   
...           ...         ...            ...                 ...   
20635       False       False          False               False   
20636       False       False          False               False   
20637       False       False          False               False   
20638       False       False          False               False   
20639       False       False          False               False   

       ocean_proximity  
0                False  
1                False  
2                False  
3                False  
4                False  
...                ...  
20635            False  
20636            False  
20637            False  
20638            False  
20639            False  

[20640 rows x 10 columns]

In [9]:
clean_data = data.dropna()
clean_data.to_csv('Spacling_clean.csv')

In [10]:
df_binary=['population','median_income']

In [12]:
df_binary

['population', 'median_income']

In [32]:
array1 = np.ones(6,dtype =np.int64)
array1

array([1, 1, 1, 1, 1, 1], dtype=int64)

In [25]:
#first no.,last no.,step size
array2 = np.arange(4,16,2)

In [33]:
#Joining 2 arrays
f = np.concatenate((array1,array2))

In [29]:
f

array([ 1,  1,  1,  1,  1,  1,  1,  4,  6,  8, 10, 12, 14], dtype=int64)

In [34]:
#No. of elements
f.size

12

In [35]:
f.shape

(12,)

In [40]:
a = np.array([[2, 4, 0],[3, 6, 9]])
b = np.array([[1, 8, 5],[0, 4, 7]])

# 3 rows and 2 cols
c = a.reshape(3,2)

In [41]:
c

array([[2, 4],
       [0, 3],
       [6, 9]])

In [42]:
# 2 rows and 3 cols
d = b.reshape(2,3)
d

array([[1, 8, 5],
       [0, 4, 7]])

In [47]:
e = np.concatenate((a,b), axis =0)
e

array([[2, 4, 0],
       [3, 6, 9],
       [1, 8, 5],
       [0, 4, 7]])

In [50]:
 A = a + b

In [51]:
B= b - a

In [52]:
A + B

array([[ 2, 16, 10],
       [ 0,  8, 14]])

In [54]:
a.sum() + b.sum()

49

In [55]:
a * 10

array([[20, 40,  0],
       [30, 60, 90]])

In [56]:
a[1,0]

3